### ISSUE TITLE
Preliminary Roadmap

### ISSUE THREAD

**Issue by appelgriebsch** [atom-ide-community/atom-ide-community.github.io#3]
With the Atom IDE Community project getting more traction we would like to share our roadmap / planning for it here. This roadmap is in a preliminary state, and has been briefly outlined on the #atom-ide Slack channel a couple of days ago. 

We provide this as an issue here, so the community can take part of the decision making process and give their direct feedback to the planning.

At the moment of writing the Atom IDE Community project hosts the following released packages:

* atom-ide-datatip 
* atom-ide-definitions
* atom-ide-signature-help

There is the planning for those:

1. polish **atom-ide-datatip**, which is already in version 0.9; 1.0 can be delivered as soon as we have diagnostic tooltips in place and fix the potential bugs with multiple overlays
2. polish **atom-ide-signature-help**. Here we are only working on bug reports and issues at the moment; looks like not many lsp have signature help implemented anyway.
3. polish **atom-ide-definitions** , in which we want to add hyperclick style functionality to jump to the source on cmd/ctrl+click.

There is one new project having started right now:

4. progress on **atom-ide-diagnostics** and provide initial set of features incl. gutter, highlighter, panel and overlay for issues in the source code. It also supports Code Actions on those issues (if available).

There are also a couple of ideas for packages to be written next:

5. start **atom-ide-console**, which can be used to stream log and diagnostic messages (error, warn, info) into a panel from various sources and optionally allows to jump to the source of the issue. Console can be used by various atom-ide packages to show output and process in a panel on the bottom of the screen.

6. start **atom-ide-outline**, which shows an outline view of the structure of the current file in the editor, and allows you to jump around easily. Project wide symbol search is also a topic we would like to cover and support.

7. start **atom-ide-formatter**, which uses the lsp to format a file or a section in a document. It provides also capabilities for automatic formatting of a file on save.

8. start **atom-ide-tester**, which offers testing features not found in the lsp, but are still required for a decent IDE experience. It automatically scans your workspace for unit test cases and can execute them on your behalf. Any issues or the status is displayed in a panel so you will always know if your source code behaves as desired. It provides language specific tester plugins and will be developed on concepts and ideas of the original [Atom Tester package(s)](https://github.com/yacut/tester).

9. start atom-ide-builder, which offers build features not found in the lsp, but are still required for a decent IDE experience. It can build your project via various build providers and shows the status of the current / recent build in a panel. It provides language specific build extensions and will be developed on concepts and ideas of the original [Atom Build package(s)](https://github.com/noseglid/atom-build).

**Comment by exploide** [comment]
Cool, thanks for filling the gap after Facebook retired. :tada: 

One question regarding atom-ide-diagnostics: How would it be different from linter-ui-default? Can't this one be reused?

Another thing: Are there plans to deliver kind of a meta package that pulls in all the other packages as dependencies? I think it would be a suboptimal user experience if one has to search and install a ton of packages manually. Besides, if one installs the packages now and then you come up with a new fancy package, the user woudn't be aware. A meta package could just deliver it as a new dependency on the next update.

**Comment by appelgriebsch** [comment]
> One question regarding atom-ide-diagnostics: How would it be different from linter-ui-default? Can't this one be reused?

Hey, thank you for your nice feedback. Yes, at the moment we are going with linter and linter-uni-default, but whereas the former has proper support for Language Server Protocol messages the ui-default is lacking some features we would like to see (such as integration with code-actions on issues).

As the linter-ui-default project hasn‘t seen any significant update for more than 12 months it would eventually be easier to just start with a drop-off that has the main features of linter-ui-default plus the missing pieces and is more consistent with our UI overall.

That said the first investigation was quite interesting as the LinterV2 and Intention package already support pluggable UIs, so we only have to take care about those parts (via provideLinterUI and provideIntentions services).

**Comment by ryanolsonx** [comment]
Great ideas regarding things unrelated to LSP (Language Server Protocol). It would _awesome_ to have some packages related to testing/building a project. 

I agree with the direction. Something to be clear on with this project in general is that we want this to be a _very_ open community. If you're a developer and you'd love to make improvements to any of these existing packages that we've created OR wish to take up one of these initiatives (namely 5-9), we'd love to have your help. This is going to be a **big** endeavor and it's going to make developing in Atom an incredible experience.

If you have any ideas for a way to improve any of these ideas, this is a great place to talk through features and what would be ideal for _you_. If you have any other ideas, we'd love to here them. It's almost like we have a nice blank slate where we, as a community, can choose the direction.

**Comment by Belar** [comment]
Hi, great progress on bringing Nuclide/Atom IDE back to live; blazing fast response to the official shut down.

> polish atom-ide-definitions , in which we want to add hyperclick style functionality to jump to the source on cmd/ctrl+click.

Since Hyperclick is still functional, I put together a provider package for `atom-ide-definitions` - https://github.com/Belar/atom-ide-click 

No idea what's the current plan; if there will be standalone, alternative Hyperclick package from community project or will it end up as a built-in, but would be happy to add/publish above to atom-ide-community packages, if it would help and fits the development scheme of course.

**Comment by ryanolsonx** [comment]
Nice! That's awesome. Would you mind integrating that into atom-ide-definitions? It really fits there. If you make a PR, I can merge it and then make you a contributor to the community 😊

**Comment by sbrl** [comment]
Regarding **atom-ide-outline**, could tree-sitter be used to generate the outline automatically?

**Comment by tonn** [comment]
Hi! I was annoyed with conflicts between atom-ide-datatip and linter-ui-default popups (like this
![image](https://user-images.githubusercontent.com/166351/56870701-3f9afe80-6a24-11e9-8503-9a38e60d9618.png) )
So I was tried to add linter messages to atom-ide-datatip popup and... and I have rewrote whole atom-ide-datatip.

Result:
![image](https://i.imgur.com/vo2c8MH.gif)

https://github.com/tonn/atom-ide-hover 
https://github.com/tonn/atom-ide-hover-datatip
https://github.com/tonn/atom-ide-hover-linter

I split package into popup-view-behavior-related (mouse/keyboard tracking, pulling data from providers) and data providers packages.
It is written on Typescript/Etch with full strict mode.

I will not publish this packages to apm with current names by myself.

And I have no idea how make pull request to your community ))... I think the best option if somebody clone my repositories into atom-ide-community, and mark atom-ide-datatip as obsolete.... of course if you want.

**Comment by michaelkonecny** [comment]
Hi,
is there going to be a package like **atom-ide-refactor**?
It seems like this wasn't finished in atom-ide, but somebody [has done some work](https://github.com/facebookarchive/atom-ide-ui/issues/145) on supporting `textDocument/rename` so maybe this could be used for a start?

**Comment by appelgriebsch** [comment]
@tonn hey, thanks for your input / idea on the diagnostics and data tip package improvements... I was heavily looking into it myself a couple of days ago. After first trying to fix it in the data tip package (as soon as it discovers that there is already an overlay shown at the given position, don't display the data tip) I was searching for a way to combine the information of rather loosely coupled components / packages. 

As of this I figured out that the data tip service already provide a mechanism to set a **priority** for the provider... so the current plan is to have the diagnostic package register as a data tip provider itself, but with an higher priority than the ide-... implementation usually do for the data tip feature (they mainly register with priority == 1). 

So as soon as the data tip package is checking for a data tip at a given position it will query the diagnostics package first, and if there is an issue will report this as usual.

This makes it possible to (easily) integrate the feature in the existing packages without having to do a huge rework / restructure of it (as you did) without loosing any existing functionality.

**Comment by tonn** [comment]
>This makes it possible to (easily) integrate the feature in the existing packages without having to do a huge rework / restructure of it (as you did) 

There was another reasons to rewrite exiting code: make it more readable (and migrate to typescript), remove strange magic-string operations with html layout (partially, there is still md-service and signature-helper), separate popup-behavior logic from popup-content logic, make more robust popup show/hide behavior on mouse events.

>without loosing any existing functionality.

As I can see I had implemented whole functional from atom-ide-datatip package... or did I miss something?

ps: I'm going to work on atom-ide-* when I will have free time. It will be great if I can benefit the community

**Comment by soriyath** [comment]
What’s the best way to contribute ?

**Comment by mallardduck** [comment]
Agree with @soriyath - it'd be nice to know more about how to contribute. I have a sense that there's a largely untapped community of old `atom-ide-ui` users that might be able to help accelerate the development process.

**Comment by appelgriebsch** [comment]
Hey everyone, as we have just started this community approach we don’t have a formal process for contributing right now. Nevertheless we highly appreciate and welcome any kind of support: testing and writing bug reports or feature request, help with spreading the word and making our community approach more widely available, checking out the roadmap and get in touch with us on the atom-ide channel on the atomio slack group in case you want to take over some of the not yet existing parts. The atom-ide channel on the slack group is also a good way to discuss with us on further topics that are not mentioned here.

**Comment by quanru** [comment]
how about node debugger?

**Comment by appelgriebsch** [comment]
> how about node debugger?
Instead of a single debug interface would be worth to look into the Debug Adapter Protocol that is heavily used in VSCode and its extensions. This DAP is kind of intermediate layer such as the LSP for programming language semantics, and would allow to reuse existing debug adapter implementations easily.

Nevertheless I assume the DAP kind of implementation might be easiest part. As the experience with the atom-ide-ui showed having a proper UI/UX for debugging is more crucial (and more effort). As of this it is not mentioned in the initial set of features / roadmap, but if someone want to take the challenge, I'm open to discuss it :)

**Comment by tonn** [comment]
Is there any chance that the project will migrate to typescript?

**Comment by adamjsimon** [comment]
I am so glad to see a community effort to pickup where facebook left off. Is there any intent or interest in a package that allows for seeing/navigating the inheritance structure of JS ES6 classes and which class in the chain provides which methods? Internally we have fiddled with extending some of the Atom Lupa project's work but the upstream project has not seen much active development in quite some time. I see some mention in the roadmap of implementing a structure view, but it appears to be scoped to the current open file (similar to the Outline view from the facebook atom ide days).

**Comment by bootsie123** [comment]
Are you thinking about adding the terminal back in?

**Comment by Belar** [comment]
> Is there any chance that the project will migrate to typescript? // @tonn 

Currently there are no organization-wide guidelines established, each package is living its own live, so decision about "flavour of JS" is with maintainer. 
However, it's totally worth looking into. Depending on response, we could put together a template for developing packages within the organization, that would of course include option to use TypeScript and potential migration.

>  Is there any intent or interest in a package [...] I see some mention in the roadmap of implementing a structure view, but it appears to be scoped to the current open file (similar to the Outline view from the facebook atom ide days) // @adamjsimon 

The roadmap is a general idea and projects listed are more of a baseline, based on the old `atom-ide-ui`, hence why the outline description mentions scope of current file. If you would like to develop more powerful package, around that functionality, there should be no problem to put it under Atom IDE Community umbrella; there is interest and everyone is welcome to contribute.

Took a quick look at the Atom Lupa (never used it) and it doesn't support outline view provided by an LSP (pretty much core of the Atom IDE), which is/was the main purpose of the original outline module. Would it conflict or be redundant if support for LSP outline was added to a Lupa-like package?

> Are you thinking about adding the terminal back in? // @bootsie123 

I don't know the full scope of the original terminal package in `atom-ide-ui`, was there something special about it? There are a few terminal packages for Atom being maintained, like [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal).

**Comment by adamjsimon** [comment]
@Belar I have looked at the Atom Lupa package and even toyed with some extension to do what I am looking for with some decent early wins, however my concern with that package is that it does not seem to be actively maintained much if at all...

**Comment by GrayJack** [comment]
Are `atom-ide-diagnostics` initial-release branch usable? If it is, how can I install and test it?

**Comment by icetee** [comment]
> Are `atom-ide-diagnostics` initial-release branch usable? If it is, how can I install and test it?

As I see it there is no meaningful code yet. I think a lot of work.

**Comment by Belar** [comment]
It's been a year since the publication of the roadmap, which seems now is a great time for an update. It may also give a positive signal that the project is not dead, although it got a bit stale for a part of 2019.

#### Status
Regarding packages released under Atom IDE Community umbrella or with started development, statuses are as follows:

- `atom-ide-datatip` - diagnostics tooltips mentioned in the roadmap are not available yet. However, package received multiple fixes, including improvements for layering and rendering.

- `atom-ide-signature-help` - it didn't change much, as it has reached stability, it's currently in "maintenance mode".

- `atom-ide-definitions` - as planned, it received support for on-click navigation. Unfortunately, Hyperclick (a click provider) is no longer maintained (it was part of the Atom IDE/Nuclide project), so in the future, it may be necessary to maintain a click provider (or find an alternative) in order to keep the feature.

- `atom-ide-outline` - supports symbols presentation with on-click navigation. Possible future features include search with filtering, sorting, and cursor follow.

- `atom-ide-vue` - language server integration for [Vue](https://vuejs.org) framework. It has good language support, but lacks quality of life features (like auto import or formatting), which require functonality (providers) unavailable in Atom IDE Community packages. However, new features can be added based on, still working, `atom-ide-ui` and be ready for community packages when these arrive.

- `atom-ide-diagnostics` - development has started, but package has never been released. Another person reached out to take it over.

Work on ideas mentioned in the roadmap, `console`, `formatter`, `tester`, and `builder` is yet to be started. To add to it, other welcome packages would be:

- `find-references` - UI for presenting symbol's references provided by language server integration package.
- `debugger` - as mentioned in the discussion above, we should aim for [Debug Adapter Protocol](https://microsoft.github.io/debug-adapter-protocol/) support.

If you know about existing, maintained packages that functionality wise fit any of the above, please share. It would be great to build a list of available alternatives to recommend, and focus development on missing solutions. For example, there are active terminal packages available in the registry, like [`platformio-ide-terminal`](https://atom.io/packages/platformio-ide-terminal) or [`termination`](https://atom.io/packages/termination).

#### Contributing

To continue on the question of contribution. It's very hard to give a meaningful answer or strict instructions that would be universal for an entire project, and it often gives a "somebody is working on it already" impression; which is usually false.

Since Atom IDE has wide variety of needs, it may be better to take it on a case by case basis. If you would like to contribute, reach out (here or through [Atom's Slack in #ide channel](https://discuss.atom.io/t/join-us-on-slack/16638) - feel free to DM me if you are unsure about a contribution) with:

- what would you like to take care of (doesn't have to be existing initiative, new ideas are welcome),
- and/or what skills do you have/would like to learn.

Let's see if this will provide a better experience for everyone who wants to participate in the project.

**Comment by aminya** [comment]
There is an atom plugin for Kite (
https://github.com/kiteco/atom-plugin) which provides:

   - 🧠 Line-of-Code Completions powered by machine learning models trained on the entire open-source code universe
   -  📝 Intelligent Snippets that automatically provide context-relevant code snippets for your function calls
   - 🔍 Instant documentation for the symbol underneath your cursor

Is there any chance to use this plugin for other languages too? It is now limited to Python.

**Comment by GrayJack** [comment]
Is there a plan to have a package to add support for inlay hints, like intellij and vscode?

**Comment by aminya** [comment]
> 
> 
> Is there a plan to have a package to add support for inlay hints, like intellij and vscode?

I think this is already possible using Linter. https://atom.io/packages/search?q=linter

**Comment by GrayJack** [comment]
No, it's not, inlay hints are like this grayish areas where it show in screen (not on hover), I found no way to do the same on atom, using ide-ui or linter

![Images](https://user-images.githubusercontent.com/17973728/71318849-22b0b100-2475-11ea-89c4-a41c010e215c.png)

**Comment by Belar** [comment]
@aminya Kite is interesting. If I remember correctly, they are working on adding support for other languages. 

Front-end/UI wise, based on plugin's description (I didn't use Kite), we are not far away. Hover info is done by `atom-ide-datatip`, signatures by `atom-ide-signatures`, and jump-to-definition by `atom-ide-definitions`. For autocomplete Kite exposes autocomplete provider, so UI is probably from Atom's `autocomplete-plus` (the one you listed). 

Documentation looks nice, a bit like a code browser - search + cursor + signature etc. Definitely possible to do as a standalone package, with "How others used this" feeling a bit tricky (depending on source, it seems to be more than a data tip example).

When it comes to the "intelligent" part, `atom-ide-` packages are on the presentation layer. If someone would develop an IDE language package that utilises machine learning, `atom-ide-` packages would work with its providers (if compatible).

---

@GrayJack Inlay hints look very handy. Unfortunately, I don't know about anything like that being available in Atom.

There is currently no plan for it on IDE Community "roadmap", with signature package already providing this info and many core packages still missing. However, it would be a great enhancement, and if someone would like to work on it, it will be a very welcome contribution.

**Comment by aminya** [comment]
> @GrayJack Inlay hints look very handy. Unfortunately, I don't know about anything like that being available in Atom.

There are similar UIs in some packages that add something to the editor. By some code reuse, we can make inlay hints.

- Juno (uber-juno_: adds result blocks to the code when something is calculated
![2020-04-03 03_51_32-Juno](https://user-images.githubusercontent.com/16418197/78342875-99bf1080-755f-11ea-995b-933e29e0bd2f.jpg)
![2020-04-03 03_51_55-Juno](https://user-images.githubusercontent.com/16418197/78342881-9b88d400-755f-11ea-8f0e-bf7dd5fabfba.jpg)


- Hydrogen: similar to Juno
![2020-04-03 03_50_46-Settings — C__Users_yahyaaba_Documents_GitHub_atom-indent-detective — Atom](https://user-images.githubusercontent.com/16418197/78342947-b6f3df00-755f-11ea-8b6f-7be8c21e4641.jpg)


- Pigments: adds color background depending on the color value.

![2020-04-03 03_53_09-Settings — C__Users_yahyaaba_Documents_GitHub_atom-indent-detective — Atom](https://user-images.githubusercontent.com/16418197/78342886-9e83c480-755f-11ea-862a-3293b28d4ab3.jpg)

- Highlight selected:  puts a square around words when selected.
![image](https://user-images.githubusercontent.com/16418197/78343011-d5f27100-755f-11ea-8775-7108a2bf6c0f.png)


> Documentation looks nice, a bit like a code browser - search + cursor + signature etc. Definitely possible to do as a standalone package, with "How others used this" feeling a bit tricky (depending on source, it seems to be more than a data tip example).

Somehow similar thing is done inside Juno:
![image](https://user-images.githubusercontent.com/16418197/78343406-6630b600-7560-11ea-8b5a-5b8567e0d493.png)

**Comment by Belar** [comment]
> We can add this feature to atom-ide-signature-help.
There are similar UIs in some packages that add something to the editor.

Ah, meant that I don't know about any package from "atom ide category" that does inlay hints. Of course, it's possible, and I agree 100% that it would be a great addition to `atom-ide-signature-help`.

> Juno (uber-juno_: adds result blocks to the code when something is calculated
> A somehow similar thing is done inside Juno

Saw Juno and [Ink](https://github.com/JunoLab/atom-ink), would be nice to be able to recommend their UI packages. However, maybe I'm wrong, it's a different approach, not modular, doesn't support IDE packages, not LSP and DAP oriented.

**Comment by Belar** [comment]
> We can add this feature to atom-ide-signature-help.
There are similar UIs in some packages that add something to the editor.

Ah, meant that I don't know about any package from "atom ide category" that does inlay hints. Of course, it's possible, and I agree 100% that it would be a great addition to `atom-ide-signature-help`.

> Juno (uber-juno_: adds result blocks to the code when something is calculated
> A somehow similar thing is done inside Juno

Saw Juno and [Ink](https://github.com/JunoLab/atom-ink), would be nice to be able to recommend their UI packages. However, maybe I'm wrong, it's a different approach, not modular, doesn't support IDE packages, not LSP and DAP oriented.

There is a room for collaboration here actually, Ink and Atom IDE have a common goal.

**Comment by aminya** [comment]
> Saw Juno and [Ink](https://github.com/JunoLab/atom-ink), would be nice to be able to recommend their UI packages. However, maybe I'm wrong, it's a different approach, not modular, doesn't support IDE packages, not LSP and DAP oriented.
> 

I have a question here. Does this modularity affect the performance or loading time? If everything was in a single package, inter-package connections could be done using JavaScript modules, but now it is done over services (correct me if I am wrong).

Actually, there is a plan to merge Ink to Julia-Client. They think this helps the loading performance.

> There is a room for collaboration here actually, Ink and Atom IDE have a common goal.

Definitely both (and the whole Atom ecosystem) can benefit from this collaboration! I look forward to helping with that.

**Comment by linjialiang** [comment]
Looking forward to the development of atom-ide-community

**Comment by UziTech** [comment]
> Hyperclick (a click provider) is no longer maintained (it was part of the Atom IDE/Nuclide project), so in the future, it may be necessary to maintain a click provider (or find an alternative) in order to keep the feature.

I wouldn't mind helping maintain a new hyperclick package. Would it be better for me to start it in a separate repo or maintain it in atom-ide-community?

**Comment by Belar** [comment]
> Would it be better for me to start it in a separate repo or maintain it in atom-ide-community?

@UziTech It's a good repo for atom-ide-community.

That said, I would like to do an update, I won't be active within the organization any more. It will be best to take all the cases with the maintainer or whoever will offer a support in the future.

**Comment by aminya** [comment]
Could someone also address my old issue for giving me access to the repositories?
https://github.com/atom-ide-community/atom-ide-datatip/issues/71

Who is in charge of keeping the organization alive?

**Comment by UziTech** [comment]
@Belar who is still an active admin in @atom-ide-community?

**Comment by lierdakil** [comment]
Okay, I have a question. Is this a ground-up from-scratch reimplementation or are you reusing bits of code/styles/etc from https://github.com/facebookarchive/atom-ide-ui?

Because if it's the former, this seems like effort duplication, which might not be entirely necessary, and if it's the latter, you have some issues with licensing, i.e. you can't just relicense bits you're using. Disclaimer: IANAL

**Comment by GrayJack** [comment]
I think it's the former

**Comment by aminya** [comment]
> That said, I would like to do an update, I won't be active within the organization any more. It will be best to take all the cases with the maintainer or whoever will offer a support in the future.

Now, I am the active admin. If anyone wants to contribute, or maintain a package please let me know.

**Comment by aminya** [comment]
@lierdakil 
> Okay, I have a question. Is this a ground-up from-scratch reimplementation or are you reusing bits of code/styles/etc from [facebookarchive/atom-ide-ui](https://github.com/facebookarchive/atom-ide-ui)?
> 

The packages that we have right now are mostly a re-implementation. The packages are in separate repositories, and the communication is only through services. For example, We have a markdown-service package, which is used by a couple of others. 

> Because if it's the former, this seems like effort duplication, which might not be entirely necessary, and if it's the latter, you have some issues with licensing, i.e. you can't just relicense bits you're using. Disclaimer: IANAL

Even if you wanted to just reuse the exact software, it is OK as long as you keep the original license in the new repository. You don't need to be a lawyer. BSD License allows **distribution of any kind** if you retain the license notice (atom-ide-community will check for the license inclusion before distribution of this kind). Check here to know more: https://en.wikipedia.org/wiki/BSD_licenses:
> BSD licenses are a family of permissive free software licenses, imposing minimal restrictions on the use and distribution of covered software.

**Comment by aminya** [comment]
I am pleased to say that we now have a parallel fork of Atom, which plans to speed up the process of development and improvements. We will release the builds under the `atom-community` name. The contributions will eventually become available in the upstream `atom` builds.
https://github.com/atom-ide-community/atom

You can check the projects to see more details about the plan: https://github.com/atom-ide-community/atom/projects
For example, we plan to include atom-ide packages to our `atom-community` builds by default.

Here is the discussion place for that project. Come chat with us! :grinning:
https://github.com/atom-ide-community/atom/issues/4

**Comment by tonn** [comment]
Glad to see such activity... may be I will return to atom someday. 
Anyway... I've already rewritten an atom-ide-datatip functional in typescript - you can use it.
There are links to repos in my comment above. Give me know if I can help

> https://github.com/tonn/atom-ide-hover
> https://github.com/tonn/atom-ide-hover-datatip
> https://github.com/tonn/atom-ide-hover-linter
> https://github.com/tonn/atom-ide-hover-codeactions

**Comment by aminya** [comment]
> Glad to see such activity... may be I will return to Atom someday.
> Anyway... I've already rewritten an atom-ide-datatip functional in typescript - you can use it.
> There are links to repos in my comment above. Give me know if I can help
> 
> > https://github.com/tonn/atom-ide-hover
> > https://github.com/tonn/atom-ide-hover-datatip
> > https://github.com/tonn/atom-ide-hover-linter
> > https://github.com/tonn/atom-ide-hover-codeactions


@tonn I invited you to the organization. Those are useful. We should consolidate these packages with [atom-ide-datatip](https://github.com/atom-ide-community/atom-ide-datatip) to prevent duplication. Then we can include them in our atom-community builds.

**Comment by lierdakil** [comment]
> License allows distribution of any kind if you retain the license notice

I checked the repos and seen MIT licences with "<your name here>" there, which I assumed are the default generated by Atom's package generator. That's why I asked -- it appears the creator of the repos didn't pay much mind to this. 

If any code at all is borrowed from atom-ide (which I am too lazy to check for at the moment), the repo (and any other distributions) must include the full text of the original licence and original copyrights. This requirement does somewhat extend to any derivative code as well, but, again, not a lawyer, and there are a lot of details to consider, like what "derivative" even means in this context.

Also, the ongoing story with [Google vs Oracle](https://en.wikipedia.org/wiki/Google_v._Oracle_America) on the issue of software copyright is rather interesting in this context. In particular, it was ruled that API are subject to copyright. Again, not a lawyer, but as far as I understand, reimplementation of an API would still require a licence from the original author under the US copyright law.

**Comment by aminya** [comment]
> I checked the repos and seen MIT licences with "<your name here>" there, which I assumed are the default generated by Atom's package generator. That's why I asked -- it appears the creator of the repos didn't pay much mind to this.

Our current packages are not using the source code of the original packages, and so there is no need to include that license. But if you personally want to use atom-ide source code here, you should include the license. 

Our releases are done automatically using semantic-release bot, and I will not add the proper token access that is needed for releasing unless I check the repositories personally.

**Comment by lierdakil** [comment]
> They use non-permissive licenses which is irrelevant to this organization.

You seem to misunderstand how it all works. There isn't a separate law for Open Source. Copyright law is the same for any kind of licence. If you break the terms of the licence, you lose the right to use the licensed software/code. Using copyrighted material without proper licence is called copyright infringement and is legally actionable. During the course of Google vs Oracle it was ruled that API is copyrighted material. So there's that.

Now, you might argue Facebook won't be interested in taking legal action. Which might be true. Still, I would argue better safe than sorry.

**Comment by aminya** [comment]
Yes. You should include the license if you are using the source code. That is obvious. Since this is getting offtopic, you might email me to continue the discussion.

**Comment by lierdakil** [comment]
> You should include the license if you are using the source code. That is obvious.

We can agree on this at least.

I'm not that interested in continuing this over email, but let me point something out.

You claim projects in this org don't use Facebook's code. This is not true. Compare and contrast:

https://github.com/atom-ide-community/atom-ide-datatip/blob/29a936f2dbf6adb2a03fbe3896d4d1e7a43a18b7/styles/atom-ide-datatips.less#L4-L14

https://github.com/facebookarchive/atom-ide-ui/blob/710f8477607d3788aeadcbdd55079925241ce40d/modules/atom-ide-ui/pkg/atom-ide-datatip/styles/datatip.less#L4-L14

Very obviously, it's the same code. Also, the rest of the file is clearly "borrowed" from Facebook's repo. And you can't argue that CSS isn't code, it's still covered by the same licence.

**Comment by aminya** [comment]
@lierdakil The discussion is out of the scope of this roadmap and does not help. The discussion should include the developers of the original repository from Facebook, which are the main stakeholders. I will include you in the emails since you seem to be interested in this.

**Comment by aminya** [comment]
FYI, the licenses for all the repositories are updated to point to the BSD notice for atom-ide-ui software in case the repository uses code from that. This will not remain in any room for ambiguity.

**Comment by paulchill** [comment]
Is there any support for remote development?
I used to use nuclide while i worked at FB and now it's an essential part of our development environment in my startup. Would love to see this being developed further

**Comment by phil-blain** [comment]
> I used to use nuclide while i worked at FB and now it's an essential part of our development environment in my startup.
@paulchill do you have any pointers on getting remote development to work in Atom in this day and age ? The "nuclide" package is not found when I go to the Install tab, so I'm not sure how to get this to work...

**Comment by aminya** [comment]
> Is there any support for remote development?
> I used to use nuclide while i worked at FB and now it's an essential part of our development environment in my startup. Would love to see this being developed further

Atom already has a good remote development support. It is officially supported by Github itself.
https://atom.io/packages/teletype

**Comment by phil-blain** [comment]
@aminya I think @paulchill was talking of this https://nuclide.io/docs/features/remote/ (at least that's what I understand). This is equivalent to the "Remote - SSH" extension in VS Code.

**Comment by sbrl** [comment]
Perhaps the `atom-sync` or `atomic-sync` packages are what you're after @paulchill?

**Comment by jeff-hykin** [comment]
@sbrl thats on the right track, but sadly its still a pretty far shot from the Remote - SSH in VS Code.
Basically you put in the remote credentials (GUI), and then you pick a folder. All other actions (including opening terminals and extension behavior) is all done exactly as-if the remote code was local.

Its going to be tough to get something like that running. I'd say remote SSH, the docker extension, and the IDE-like stuff are the "killer-apps" of VS Code that are going to take the most work to replicate.

**Comment by jeff-hykin** [comment]
Is there a link to the #atom-ide Slack that I could join with?

**Comment by aminya** [comment]
You can join using this link:
discord.gg/ytUmurh

**Comment by aminya** [comment]
> Is there any support for remote development?
> I used to use nuclide while i worked at FB and now it's an essential part of our development environment in my startup. Would love to see this being developed further

@h3imdall provides a great package for remote development. Check it out!
https://atom.io/packages/ftp-remote-edit

**Comment by jeff-hykin** [comment]
@aminya that looks like an awesome extension! I think something like that could compete to some degree with vscodes remote ssh.

**Comment by aminya** [comment]
Hey everyone! I am closing this issue in favor of the new feature of GitHub, "discussions".

https://github.com/atom-ide-community/atom/discussions
